# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('previousBlockHash', models.CharField(max_length=64)),
                ('timeStamp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('publicKeyOfSender', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=140)),
                ('postHash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('timeStamp', models.IntegerField()),
                ('blockIndex', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
