# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('previousBlockHash', models.CharField(max_length=64)),
                ('timeStamp', models.IntegerField(null=True)),
                ('blockHash', models.CharField(max_length=64)),
                ('nonce', models.IntegerField(null=True)),
                ('target', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('secondsSinceLastInteraction', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('publicKeyOfSender', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=140)),
                ('postHash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('timeStamp', models.IntegerField()),
                ('blockIndex', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
