# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousBlockHash', models.CharField(max_length=64)),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('publicKeyOfSender', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=128)),
                ('timeStamp', models.DateField()),
                ('content', models.CharField(max_length=140)),
                ('postHash', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
