# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedgerBoardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='timeStamp',
            field=models.IntegerField(null=True),
        ),
    ]
