# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedgerBoardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumTitle', models.CharField(max_length=64)),
                ('datumContent', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='timeOfBlackList',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
