# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedgerBoardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('defaultStatus', models.BinaryField()),
            ],
        ),
    ]
