# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LedgerBoardApp', '0002_auto_20170704_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='blockHash',
            field=models.CharField(max_length=512),
        ),
    ]
